# Generated by Django 5.1 on 2024-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigoProduto', models.AutoField(primary_key=True, serialize=False)),
                ('tituloProduto', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('imagensProduto', models.JSONField(default=dict)),
                ('categoriaProduto', models.CharField(max_length=255)),
                ('classificacaoProduto', models.CharField(default='Desconhecido', max_length=255)),
                ('exibirHome', models.BooleanField(default=True)),
            ],
        ),
    ]
